// <auto-generated />
using IQ_Test.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IQ_Test.Migrations
{
    [DbContext(typeof(QuestionContext))]
    [Migration("20201120172521_QuestionMigration")]
    partial class QuestionMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IQ_Test.Models.QuestionModel", b =>
                {
                    b.Property<int>("Qid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Correctans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("option4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Qid");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
